import type { Metadata } from "next";
import { Inter, Poppins, Tinos } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import { ReduxProvider } from "./ReduxProvider";


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BlogVerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <ReduxProvider>
            {children}
            <Toaster />
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
